version: "3.12"
services:
  grafana-loki:
    depends_on:
    - loki
    deploy:
      mode: global
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: loki
      placement:
        constraints:
        - node.labels.services.logstack_grafana_loki_server == true
    environment:
      TARGET_TASK_ADDR: replica-{{.Node.ID}}.grafana-loki-internal:3100
    hostname: grafana-loki.local
    image: swarmlibs/docker-task-proxy:main
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana: null
      logstack_gwnetwork: null
      prometheus_gwnetwork: null
    ports:
    - target: 80
      published: 3100
  grafana-loki-server:
    command:
    - -config.expand-env
    - -config.file=/etc/loki/grafana-loki-config.yaml
    - -common.storage.ring.store=memberlist
    - -memberlist.bind-port=7946
    - -memberlist.join=dns+tasks.grafana-loki-server:7946
    - -memberlist.rejoin-interval=30s
    - -memberlist.dead-node-reclaim-time=30s
    - -memberlist.abort-if-join-fails
    configs:
    - source: grafana-loki-docker-entrypoint-shim.sh
      target: /docker-entrypoint-shim.sh
      mode: 365
    - source: grafana-loki-config.yaml
      target: /etc/loki/grafana-loki-config.yaml
    - source: gf-provisioning-datasource-grafana-loki
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    entrypoint:
    - /docker-entrypoint-shim.sh
    environment:
      GF_LOKI_ADVERTISE_INTERFACE: eth0
      GF_LOKI_COMMON_STORAGE_RING_REPLICATION_FACTOR: null
      GF_LOKI_DOCKER_STACK_NAMESPACE: '{{ index .Service.Labels "com.docker.stack.namespace"}}'
    hostname: replica-{{.Node.ID}}.grafana-loki-internal
    image: grafana/loki:2.9.9
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana: null
    stop_signal: SIGTERM
    volumes:
    - type: volume
      source: grafana-loki-data
      target: /loki
  promtail:
    command:
    - -ec
    - /usr/bin/promtail -config.expand-env=true -config.file=/etc/promtail/promtail-config.yaml
      -server.enable-runtime-reload
    configs:
    - source: promtail-config.yaml
      target: /etc/promtail/promtail-config.yaml
    - source: prometheus-promtail
    deploy:
      mode: global
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: grafana-loki-promtail
      placement:
        max_replicas_per_node: 1
    entrypoint:
    - /bin/sh
    environment:
      PROMTAIL_CLIENT_TENANT_ID: null
      PROMTAIL_CLIENT_URL: null
      PROMTAIL_ENABLE_TRACING: null
    hostname: replica-{{.Node.ID}}.promtail.local
    image: grafana/promtail:2.9.9
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      logstack_gwnetwork: null
      prometheus_gwnetwork: null
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    - type: volume
      source: promtail-data
      target: /promtail
networks:
  grafana: {}
  logstack_gwnetwork:
    name: logstack_gwnetwork
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
volumes:
  grafana-loki-data: {}
  promtail-data: {}
configs:
  gf-provisioning-datasource-grafana-loki:
    name: gf-provisioning-datasource-grafana-loki-v1
    file: grafana-loki/grafana/grafana-loki.yml
    labels:
      io.grafana.provisioning.datasource: "true"
  grafana-loki-config.yaml:
    name: grafana-loki-config.yaml-v1
    file: grafana-loki/grafana-loki/grafana-loki-config.yaml
  grafana-loki-docker-entrypoint-shim.sh:
    name: grafana-loki-docker-entrypoint-shim.sh-v1
    file: grafana-loki/grafana-loki/docker-entrypoint-shim.sh
  prometheus-promtail:
    name: prometheus-promtail-v1
    file: promtail/prometheus/promtail.yml
    labels:
      io.prometheus.scrape_config: "true"
  promtail-config.yaml:
    name: promtail-config.yaml-v1
    file: promtail/promtail/promtail-config.yaml
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-deploy:
  placement:
    max_replicas_per_node: 1
  replicas: 1
x-grafana-subservice-deploy:
  mode: global
  placement:
    constraints:
    - node.labels.services.logstack_grafana_loki_server == true
