version: "3.12"
services:
  grafana-loki:
    depends_on:
    - loki
    deploy:
      mode: global
      labels:
        io.prometheus.enabled: "true"
        io.prometheus.job_name: loki
      placement:
        constraints:
        - node.labels.services.logstack_grafana_loki_server == true
    environment:
      TARGET_TASK_ADDR: replica-{{.Node.ID}}.grafana-loki-internal:3100
    hostname: grafana-loki.local
    image: swarmlibs/docker-task-proxy:main
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana: null
      logstack_gwnetwork: null
      prometheus_gwnetwork: null
    ports:
    - target: 80
      published: 3100
  grafana-loki-server:
    command:
    - -config.expand-env
    - -config.file=/etc/loki/grafana-loki-config.yaml
    - -common.storage.ring.store=memberlist
    - -memberlist.bind-port=7946
    - -memberlist.join=dns+tasks.grafana-loki-server:7946
    - -memberlist.rejoin-interval=30s
    - -memberlist.dead-node-reclaim-time=30s
    - -memberlist.abort-if-join-fails
    configs:
    - source: grafana-loki-docker-entrypoint-shim.sh
      target: /docker-entrypoint-shim.sh
      mode: 365
    - source: grafana-loki-config.yaml
      target: /etc/loki/grafana-loki-config.yaml
    - source: gf-provisioning-datasource-grafana-loki
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      rollback_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 15s
        max_failure_ratio: 0.1
      restart_policy:
        condition: any
        delay: 30s
        window: 15s
      placement:
        max_replicas_per_node: 1
    entrypoint:
    - /docker-entrypoint-shim.sh
    environment:
      GF_LOKI_ADVERTISE_INTERFACE: eth0
      GF_LOKI_COMMON_STORAGE_RING_REPLICATION_FACTOR: ${GF_LOKI_COMMON_STORAGE_RING_REPLICATION_FACTOR}
      GF_LOKI_DOCKER_STACK_NAMESPACE: '{{ index .Service.Labels "com.docker.stack.namespace"}}'
    hostname: replica-{{.Node.ID}}.grafana-loki-internal
    image: grafana/loki:2.9.9
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      grafana: null
    stop_signal: SIGTERM
    volumes:
    - type: volume
      source: grafana-loki-data
      target: /loki
networks:
  grafana: {}
  logstack_gwnetwork:
    name: logstack_gwnetwork
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
volumes:
  grafana-loki-data: {}
configs:
  gf-provisioning-datasource-grafana-loki:
    name: gf-provisioning-datasource-grafana-loki-v1
    file: ./grafana/grafana-loki.yml
    labels:
      io.grafana.provisioning.datasource: "true"
  grafana-loki-config.yaml:
    name: grafana-loki-config.yaml-v1
    file: ./grafana-loki/grafana-loki-config.yaml
  grafana-loki-docker-entrypoint-shim.sh:
    name: grafana-loki-docker-entrypoint-shim.sh-v1
    file: ./grafana-loki/docker-entrypoint-shim.sh
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
x-deploy:
  placement:
    max_replicas_per_node: 1
  replicas: 1
x-grafana-subservice-deploy:
  mode: global
  placement:
    constraints:
    - node.labels.services.logstack_grafana_loki_server == true
