server:
  log_level: info
  log_format: logfmt
  http_listen_port: 9080

clients:
  - url: ${PROMTAIL_CLIENT_URL:-http://grafana-loki-gateway.internal:3100/loki/api/v1/push}
    tenant_id: ${PROMTAIL_CLIENT_TENANT_ID:-fake}

positions:
  filename: /promtail/positions.yaml

tracing:
  enabled: ${PROMTAIL_ENABLE_TRACING:-false}

scrape_configs:
  - job_name: docker

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s

    pipeline_stages:
      - docker: {}

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_docker_container_label_com_(docker_.*)

      # Rename labels docker_swarm_(.+) to dockerswarm_$1
      # This is useful for compatibility with "dockerswarm-tasks.yml" relabeling
      - action: labelmap
        regex: __meta_docker_container_label_com_docker_swarm_(.+)
        replacement: dockerswarm_$1
      - action: labeldrop
        regex: (^docker_swarm_.+)

      # ================================================================================
      # Docker Swarm compatible relabeling
      # - dockerswarm_task_name
      # ================================================================================

      # Set "task" label to "<service_name>.<task_slot>
      - source_labels:
        - dockerswarm_task_name
        target_label: task
        regex: (.+)\.(.+)\.(.+)
        replacement: $1.$2

      # ================================================================================
      # Kubernetes compatible relabeling
      # - namespace
      # - deployment
      # - pod
      # ================================================================================
      # # Set Kubernetes's Namespace with "com.docker.stack.namespace" label
      - source_labels:
        - __meta_docker_container_label_com_docker_stack_namespace
        target_label: namespace

      # Set Kubernetes's Deployment with "com.docker.stack.namespace" label
      - source_labels:
        - __meta_docker_container_label_com_docker_swarm_service_name
        target_label: deployment

      # Set Kubernetes's Service with "com.docker.stack.namespace" label
      - source_labels:
        - __meta_docker_container_label_com_docker_swarm_service_name
        target_label: service

      # Set Kubernetes's Pod Name with Docker Swarm's Service Name
      - source_labels:
        - dockerswarm_task_name
        target_label: pod
        regex: (.*)

      # ================================================================================
      # Grafana Loki log volume support
      # ================================================================================
      - source_labels:
        - __meta_docker_container_label_com_docker_swarm_service_name
        target_label: service_name
