# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Loki Promtail
  # https://github.com/grafana/loki
  # ====================================================

  promtail:
    image: swarmlibs/promtail:main
    environment:
      - GF_LOKI_HOST=grafana-loki.local
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      labels:
        io.prometheus.role: "promtail"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
    logging: *x-default-logging
    # ports:
    #   - published: 9080
    #     target: 9080
    #     mode: host
    hostname: replica-{{.Task.Slot}}.promtail.local
    networks:
      logstack_gwnetwork:
        aliases:
          - promtail.local
      prometheus_gwnetwork:
        aliases:
          - promtail.local
    configs:
      - prometheus-promtail
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: promtail-data
        target: /promtail

configs:
  prometheus-promtail:
    name: prometheus-promtail-v1
    file: ./prometheus/promtail.yml
    labels:
      - "io.prometheus.scrape_config=true"

volumes:
  promtail-data:

networks:
  logstack_gwnetwork:
    name: logstack_gwnetwork
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
