# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

x-default-logging: &x-default-logging
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

services:

  # ====================================================
  # Loki Promtail
  # https://github.com/grafana/loki
  # ====================================================

  grafana-loki-promtail:
    image: grafana/promtail:2.9.9
    entrypoint: /bin/sh
    command: -ec "/usr/bin/promtail -server.enable-runtime-reload -config.expand-env=true -config.file=/etc/promtail/promtail-config.yaml"
    environment:
      PROMTAIL_ENABLE_TRACING:
      PROMTAIL_CLIENT_URL:
      PROMTAIL_CLIENT_TENANT_ID:
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      labels:
        io.prometheus.role: "grafana-loki-promtail"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.dockerswarm-services.should_be_probed: "false"
    logging: *x-default-logging
    # ports:
    #   - published: 9080
    #     target: 9080
    #     mode: host
    hostname: replica-{{.Node.ID}}.promtail.local
    networks:
      logstack_gwnetwork:
        aliases:
          - promtail.local
      prometheus_gwnetwork:
        aliases:
          - promtail.local
    configs:
      - source: promtail-config.yaml
        target: /etc/promtail/promtail-config.yaml
      - source: prometheus-promtail
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: promtail-data
        target: /promtail

configs:
  promtail-config.yaml:
    name: promtail-config.yaml-v1
    file: ./configs/promtail-config.yaml

  # Prometheus scrape config
  prometheus-promtail:
    name: prometheus-promtail-v1
    file: ./prometheus/promtail.yml
    labels:
      - "io.prometheus.scrape_config=true"

volumes:
  promtail-data:

networks:
  logstack_gwnetwork:
    name: logstack_gwnetwork
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
