version: "3.12"
services:
  promtail:
    command:
    - -ec
    - /usr/bin/promtail -config.expand-env=true -config.file=/etc/promtail/promtail-config.yaml
      -server.enable-runtime-reload
    configs:
    - source: promtail-config.yaml
      target: /etc/promtail/promtail-config.yaml
    - source: prometheus-promtail
    deploy:
      mode: global
      labels:
        io.prometheus.dockerswarm-services.should_be_probed: "false"
        io.prometheus.dockerswarm-tasks.should_be_scraped: "false"
        io.prometheus.role: grafana-loki-promtail
      placement:
        max_replicas_per_node: 1
    entrypoint:
    - /bin/sh
    environment:
      PROMTAIL_CLIENT_TENANT_ID: ${PROMTAIL_CLIENT_TENANT_ID}
      PROMTAIL_CLIENT_URL: ${PROMTAIL_CLIENT_URL}
      PROMTAIL_ENABLE_TRACING: ${PROMTAIL_ENABLE_TRACING}
    hostname: replica-{{.Node.ID}}.promtail.local
    image: grafana/promtail:2.9.9
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 12m
    networks:
      logstack_gwnetwork: null
      prometheus_gwnetwork: null
    ports:
    - mode: host
      target: 9080
      published: 9080
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
    - type: volume
      source: promtail-data
      target: /promtail
networks:
  logstack_gwnetwork:
    name: logstack_gwnetwork
    external: true
  prometheus_gwnetwork:
    name: prometheus_gwnetwork
    external: true
volumes:
  promtail-data: {}
configs:
  prometheus-promtail:
    name: prometheus-promtail-v1
    file: ./prometheus/promtail.yml
    labels:
      io.prometheus.scrape_config: "true"
  promtail-config.yaml:
    name: promtail-config.yaml-v1
    file: ./promtail/promtail-config.yaml
x-default-logging:
  driver: json-file
  options:
    max-file: "5"
    max-size: 12m
