apiVersion: 1

deleteDatasources:
  - name: Logstack - Grafana Loki
    orgId: 1
  - name: Logstack - Grafana Loki PromQL
    orgId: 1

prune: true

datasources:
  - uid: logstack-grafana-loki
    name: Logstack - Grafana Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://grafana-loki.local
    version: 1
    isDefault: false
    editable: false
  - uid: logstack-grafana-loki-promql
    name: Logstack - Grafana Loki PromQL
    type: prometheus
    access: proxy
    orgId: 1
    url: http://grafana-loki.local/loki
    version: 1
    isDefault: false
    editable: false
    jsonData:
      manageAlerts: false
